package seasonal.parade.halloween.render;

import net.minecraft.src.Entity;
import net.minecraft.src.MathHelper;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelHeadless extends ModelBase
{
	//fields
    ModelRenderer horsebody;
    ModelRenderer horsehead;
    ModelRenderer horseneck;
    ModelRenderer horseear1;
    ModelRenderer horseear2;
    ModelRenderer horselegleft1;
    ModelRenderer horselegleft2;
    ModelRenderer horselegright1;
    ModelRenderer horselegright2;
    ModelRenderer horsetail;
    ModelRenderer humanbody;
    ModelRenderer humanrightarm;
    ModelRenderer humanleftarm;
    ModelRenderer humanrightleg;
    ModelRenderer humanleftleg;
    ModelRenderer humanlefthead;
    ModelRenderer humanrightspear;
    ModelRenderer humancoatfront;
    ModelRenderer humancoatside;
    ModelRenderer humancoatside2;
    ModelRenderer humancoattop;
      public ModelHeadless()
      {
        horsebody = new ModelRenderer(this, 0, 21);
        horsebody.addBox(0F, -0.5F, 0F, 4, 4, 7);
        horsebody.setRotationPoint(-1.5F, 17F, -2F);
        horsebody.rotateAngleX = 0F;
        horsebody.rotateAngleY = 0F;
        horsebody.rotateAngleZ = 0F;
        horsebody.mirror = false;
        horsehead = new ModelRenderer(this, 0, 0);
        horsehead.addBox(-1F, -2F, -4F, 3, 3, 4);
        horsehead.setRotationPoint(0F, 16F, -3F);
        horsehead.rotateAngleX = 0F;
        horsehead.rotateAngleY = 0F;
        horsehead.rotateAngleZ = 0F;
        horsehead.mirror = false;
        horseneck = new ModelRenderer(this, 0, 26);
        horseneck.addBox(-0.5F, -1F, -1F, 2, 2, 4);
        horseneck.setRotationPoint(0F, 16F, -3F);
        horseneck.rotateAngleX = -0.69813F;
        horseneck.rotateAngleY = 0F;
        horseneck.rotateAngleZ = 0F;
        horseneck.mirror = false;
        horseear1 = new ModelRenderer(this, 0, 30);
        horseear1.addBox(-1F, -2.5F, -1.5F, 1, 1, 1);
        horseear1.setRotationPoint(0F, 16F, -3F);
        horseear1.rotateAngleX = 0F;
        horseear1.rotateAngleY = 0F;
        horseear1.rotateAngleZ = 0F;
        horseear1.mirror = false;
        horseear2 = new ModelRenderer(this, 0, 30);
        horseear2.addBox(1F, -2.5F, -1.5F, 1, 1, 1);
        horseear2.setRotationPoint(0F, 16F, -3F);
        horseear2.rotateAngleX = 0F;
        horseear2.rotateAngleY = 0F;
        horseear2.rotateAngleZ = 0F;
        horseear2.mirror = false;
        horselegleft1 = new ModelRenderer(this, 0, 26);
        horselegleft1.addBox(0F, 0F, 0F, 1, 4, 2);
        horselegleft1.setRotationPoint(1.5F, 20F, -2F);
        horselegleft1.rotateAngleX = 0F;
        horselegleft1.rotateAngleY = 0F;
        horselegleft1.rotateAngleZ = 0F;
        horselegleft1.mirror = true;
        horselegleft2 = new ModelRenderer(this, 0, 26);
        horselegleft2.addBox(0F, 0F, 0F, 1, 4, 2);
        horselegleft2.setRotationPoint(1.5F, 20F, 3F);
        horselegleft2.rotateAngleX = 0F;
        horselegleft2.rotateAngleY = 0F;
        horselegleft2.rotateAngleZ = 0F;
        horselegleft2.mirror = true;
        horselegright1 = new ModelRenderer(this, 0, 26);
        horselegright1.addBox(-1F, 0F, 0F, 1, 4, 2);
        horselegright1.setRotationPoint(-0.5F, 20F, -2F);
        horselegright1.rotateAngleX = 0F;
        horselegright1.rotateAngleY = 0F;
        horselegright1.rotateAngleZ = 0F;
        horselegright1.mirror = false;
        horselegright2 = new ModelRenderer(this, 0, 26);
        horselegright2.addBox(-1F, 0F, 0F, 1, 4, 2);
        horselegright2.setRotationPoint(-0.5F, 20F, 3F);
        horselegright2.rotateAngleX = 0F;
        horselegright2.rotateAngleY = 0F;
        horselegright2.rotateAngleZ = 0F;
        horselegright2.mirror = false;
        horsetail = new ModelRenderer(this, 0, 25);
        horsetail.addBox(1F, 1.5F, 6F, 2, 5, 2);
        horsetail.setRotationPoint(-1.5F, 17F, -2F);
        horsetail.rotateAngleX = 0.31416F;
        horsetail.rotateAngleY = 0F;
        horsetail.rotateAngleZ = 0F;
        horsetail.mirror = false;
        humanbody = new ModelRenderer(this, 48, 16);
        humanbody.addBox(0.5F, -0.5F, 0.5F, 4, 6, 2);
        humanbody.setRotationPoint(-2F, 10F, 0F);
        humanbody.rotateAngleX = 0F;
        humanbody.rotateAngleY = 0F;
        humanbody.rotateAngleZ = 0F;
        humanbody.mirror = false;
        humanrightarm = new ModelRenderer(this, 56, 0);
        humanrightarm.addBox(-1.5F, -0.5F, 1F, 2, 5, 2);
        humanrightarm.setRotationPoint(-2F, 10F, 0F);
        humanrightarm.rotateAngleX = 0F;
        humanrightarm.rotateAngleY = 0F;
        humanrightarm.rotateAngleZ = 0.05236F;
        humanrightarm.mirror = false;
        humanleftarm = new ModelRenderer(this, 56, 0);
        humanleftarm.addBox(-0.5F, -0.5F, 1F, 2, 5, 2);
        humanleftarm.setRotationPoint(3F, 9F, 2F);
        humanleftarm.rotateAngleX = -1.5708F;
        humanleftarm.rotateAngleY = 0F;
        humanleftarm.rotateAngleZ = -0.05236F;
        humanleftarm.mirror = true;
        humanrightleg = new ModelRenderer(this, 50, 9);
        humanrightleg.addBox(0.5F, -0.5F, -4F, 2, 2, 5);
        humanrightleg.setRotationPoint(-2F, 15F, 2F);
        humanrightleg.rotateAngleX = 0.08727F;
        humanrightleg.rotateAngleY = 0.31416F;
        humanrightleg.rotateAngleZ = 0F;
        humanrightleg.mirror = false;
        humanleftleg = new ModelRenderer(this, 50, 9);
        humanleftleg.addBox(-0.5F, -0.5F, -4.5F, 2, 2, 5);
        humanleftleg.setRotationPoint(1F, 15F, 2F);
        humanleftleg.rotateAngleX = 0.08727F;
        humanleftleg.rotateAngleY = -0.31416F;
        humanleftleg.rotateAngleZ = 0F;
        humanleftleg.mirror = false;
        humanlefthead = new ModelRenderer(this, 52, 26);
        humanlefthead.addBox(-1F, 0.5F, -7F, 3, 3, 3);
        humanlefthead.setRotationPoint(3F, 9F, 2F);
        humanlefthead.rotateAngleX = 0F;
        humanlefthead.rotateAngleY = 0F;
        humanlefthead.rotateAngleZ = -0.05236F;
        humanlefthead.mirror = false;
        humanrightspear = new ModelRenderer(this, 22, 20);
        humanrightspear.addBox(-1F, 3F, -7F, 1, 1, 11);
        humanrightspear.setRotationPoint(-2F, 10F, 0F);
        humanrightspear.rotateAngleX = 0F;
        humanrightspear.rotateAngleY = 0F;
        humanrightspear.rotateAngleZ = 0.05236F;
        humanrightspear.mirror = false;
        humancoatfront = new ModelRenderer(this, 48, 0);
        humancoatfront.addBox(0.5F, -0.5F, -0.5F, 4, 4, 0);
        humancoatfront.setRotationPoint(-2F, 10F, 0F);
        humancoatfront.rotateAngleX = 0.05236F;
        humancoatfront.rotateAngleY = 0F;
        humancoatfront.rotateAngleZ = 0F;
        humancoatfront.mirror = false;
        humancoatside = new ModelRenderer(this, 36, -6);
        humancoatside.addBox(0.5F, -0.5F, -0.5F, 0, 4, 6);
        humancoatside.setRotationPoint(-2F, 10F, 0F);
        humancoatside.rotateAngleX = 0.05236F;
        humancoatside.rotateAngleY = 0F;
        humancoatside.rotateAngleZ = 0F;
        humancoatside.mirror = false;
        humancoatside2 = new ModelRenderer(this, 36, -6);
        humancoatside2.addBox(4.5F, -0.5F, -0.5F, 0, 4, 6);
        humancoatside2.setRotationPoint(-2F, 10F, 0F);
        humancoatside2.rotateAngleX = 0.05236F;
        humancoatside2.rotateAngleY = 0F;
        humancoatside2.rotateAngleZ = 0F;
        humancoatside2.mirror = true;
        humancoattop = new ModelRenderer(this, 24, 0);
        humancoattop.addBox(0.5F, -0.5F, -0.5F, 4, 0, 4);
        humancoattop.setRotationPoint(-2F, 10F, 0F);
        humancoattop.rotateAngleX = 0.05236F;
        humancoattop.rotateAngleY = 0F;
        humancoattop.rotateAngleZ = 0F;
        humancoattop.mirror = false;
      }

      public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        horsebody.render(f5);
        horsehead.render(f5);
        horseneck.render(f5);
        horseear1.render(f5);
        horseear2.render(f5);
        horselegleft1.render(f5);
        horselegleft2.render(f5);
        horselegright1.render(f5);
        horselegright2.render(f5);
        horsetail.render(f5);
        humanbody.render(f5);
        humanrightarm.render(f5);
        humanleftarm.render(f5);
        humanrightleg.render(f5);
        humanleftleg.render(f5);
        humanlefthead.render(f5);
        humanrightspear.render(f5);
        humancoatfront.render(f5);
        humancoatside.render(f5);
        humancoatside2.render(f5);
        humancoattop.render(f5);
      }

      public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.setRotationAngles(f, f1, f2, f3, f4, f5);
        horselegleft1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        horselegleft2.rotateAngleX = MathHelper.cos(f * 0.6662F + 3.141593F) * 1.4F * f1;
        horselegright1.rotateAngleX = MathHelper.cos(f * 0.6662F + 3.141593F) * 1.4F * f1;
        horselegright2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        humanrightarm.rotateAngleX = MathHelper.cos(f * 0.6662F + 3.141593F) * 2.0F * f1 * 0.5F;
        humanrightspear.rotateAngleX = humanrightarm.rotateAngleX;
      }
}
